In [5]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from sklearn.preprocessing import KBinsDiscretizer
from sklearn.preprocessing import LabelEncoder
from scipy.stats import zscore
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn import linear_model
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error , r2_score, accuracy_score

In [6]:
df=pd.read_csv(r"C:\Users\Dell\OneDrive\Desktop\Python week1\Python week 3+\Amazon Data Set.csv")
df.head()

,product_id,product_name,category,discounted_price,actual_price,discount_percentage,rating,rating_count,about_product,user_id,user_name,review_id,review_title,review_content,img_link,product_link
0,B07JW9H4J1,Wayona Nylon Braided USB to Lightning Fast Cha...,Computers&Accessories|Accessories&Peripherals|...,₹399,"₹1,099",64%,4.2,"24,269",High Compatibility : Compatible With iPhone 12...,"AG3D6O4STAQKAY2UVGEUV46KN35Q,AHMY5CWJMMK5BJRBB...","Manav,Adarsh gupta,Sundeep,S.Sayeed Ahmed,jasp...","R3HXWT0LRP0NMF,R2AJM3LFTLZHFO,R6AQJGUP6P86,R1K...","Satisfied,Charging is really fast,Value for mo...",Looks durable Charging is fine tooNo complains...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Wayona-Braided-WN3LG1-Sy...
1,B098NS6PVG,Ambrane Unbreakable 60W / 3A Fast Charging 1.5...,Computers&Accessories|Accessories&Peripherals|...,₹199,₹349,43%,4,"43,994","Compatible with all Type C enabled devices, be...","AECPFYFQVRUWC3KGNLJIOREFP5LQ,AGYYVPDD7YG7FYNBX...","ArdKn,Nirbhay kumar,Sagar Viswanathan,Asp,Plac...","RGIQEG07R9HS2,R1SMWZQ86XIN8U,R2J3Y1WL29GWDE,RY...","A Good Braided Cable for Your Type C Device,Go...",I ordered this cable to connect my phone to An...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Ambrane-Unbreakable-Char...
2,B096MSW6CT,Sounce Fast Phone Charging Cable & Data Sync U...,Computers&Accessories|Accessories&Peripherals|...,₹199,"₹1,899",90%,3.9,"7,928",【 Fast Charger& Data Sync】-With built-in safet...,"AGU3BBQ2V2DDAMOAKGFAWDDQ6QHA,AESFLDV2PT363T2AQ...","Kunal,Himanshu,viswanath,sai niharka,saqib mal...","R3J3EQQ9TZI5ZJ,R3E7WBGK7ID0KV,RWU79XKQ6I1QF,R2...","Good speed for earlier versions,Good Product,W...","Not quite durable and sturdy,https://m.media-a...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Sounce-iPhone-Charging-C...
3,B08HDJ86NZ,boAt Deuce USB 300 2 in 1 Type-C & Micro USB S...,Computers&Accessories|Accessories&Peripherals|...,₹329,₹699,53%,4.2,"94,363",The boAt Deuce USB 300 2 in 1 cable is compati...,"AEWAZDZZJLQUYVOVGBEUKSLXHQ5A,AG5HTSFRRE6NL3M5S...","Omkar dhale,JD,HEMALATHA,Ajwadh a.,amar singh ...","R3EEUZKKK9J36I,R3HJVYCLYOY554,REDECAZ7AMPQC,R1...","Good product,Good one,Nice,Really nice product...","Good product,long wire,Charges good,Nice,I bou...",https://m.media-amazon.com/images/I/41V5FtEWPk...,https://www.amazon.in/Deuce-300-Resistant-Tang...
4,B08CF3B7N1,Portronics Konnect L 1.2M Fast Charging 3A 8 P...,Computers&Accessories|Accessories&Peripherals|...,₹154,₹399,61%,4.2,"16,905",[CHARGE & SYNC FUNCTION]- This cable comes wit...,"AE3Q6KSUK5P75D5HFYHCRAOLODSA,AFUGIFH5ZAFXRDSZH...","rahuls6099,Swasat Borah,Ajay Wadke,Pranali,RVK...","R1BP4L2HH9TFUP,R16PVJEXKV6QZS,R2UPDB81N66T4P,R...","As good as original,Decent,Good one for second...","Bought this instead of original apple, does th...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Portronics-Konnect-POR-1...

In [7]:
df.tail()

,product_id,product_name,category,discounted_price,actual_price,discount_percentage,rating,rating_count,about_product,user_id,user_name,review_id,review_title,review_content,img_link,product_link
1460,B08L7J3T31,Noir Aqua - 5pcs PP Spun Filter + 1 Spanner | ...,Home&Kitchen|Kitchen&HomeAppliances|WaterPurif...,₹379,₹919,59%,4,"1,090",SUPREME QUALITY 90 GRAM 3 LAYER THIK PP SPUN F...,"AHITFY6AHALOFOHOZEOC6XBP4FEA,AFRABBODZJZQB6Z4U...","Prabha ds,Raghuram bk,Real Deal,Amazon Custome...","R3G3XFHPBFF0E8,R3C0BZCD32EIGW,R2EBVBCN9QPD9R,R...","Received the product without spanner,Excellent...","I received product without spanner,Excellent p...",https://m.media-amazon.com/images/I/41fDdRtjfx...,https://www.amazon.in/Noir-Aqua-Spanner-Purifi...
1461,B01M6453MB,Prestige Delight PRWO Electric Rice Cooker (1 ...,Home&Kitchen|Kitchen&HomeAppliances|SmallKitch...,"₹2,280","₹3,045",25%,4.1,"4,118","230 Volts, 400 watts, 1 Year","AFG5FM3NEMOL6BNFRV2NK5FNJCHQ,AGEINTRN6Z563RMLH...","Manu Bhai,Naveenpittu,Evatira Sangma,JAGANNADH...","R3DDL2UPKQ2CK9,R2SYYU1OATVIU5,R1VM993161IYRW,R...","ok,everything was good couldn't return bcoz I ...","ok,got everything as mentioned but the measuri...",https://m.media-amazon.com/images/I/41gzDxk4+k...,https://www.amazon.in/Prestige-Delight-PRWO-1-...
1462,B009P2LIL4,Bajaj Majesty RX10 2000 Watts Heat Convector R...,"Home&Kitchen|Heating,Cooling&AirQuality|RoomHe...","₹2,219","₹3,080",28%,3.6,468,International design and styling|Two heat sett...,"AGVPWCMAHYQWJOQKMUJN4DW3KM5Q,AF4Q3E66MY4SR7YQZ...","Nehal Desai,Danish Parwez,Amazon Customer,Amaz...","R1TLRJVW4STY5I,R2O455KRN493R1,R3Q5MVGBRIAS2G,R...","very good,Work but front melt after 2 month,Go...","plastic but cool body ,u have to find sturdy s...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Bajaj-RX-10-2000-Watt-Co...
1463,B00J5DYCCA,Havells Ventil Air DSP 230mm Exhaust Fan (Pist...,"Home&Kitchen|Heating,Cooling&AirQuality|Fans|E...","₹1,399","₹1,890",26%,4,"8,031",Fan sweep area: 230 MM ; Noise level: (40 - 45...,"AF2JQCLSCY3QJATWUNNHUSVUPNQQ,AFDMLUXC5LS5RXDJS...","Shubham Dubey,E.GURUBARAN,Mayank S.,eusuf khan...","R39Q2Y79MM9SWK,R3079BG1NIH6MB,R29A31ZELTZNJM,R...","Fan Speed is slow,Good quality,Good product,go...",I have installed this in my kitchen working fi...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Havells-Ventilair-230mm-...
1464,B01486F4G6,Borosil Jumbo 1000-Watt Grill Sandwich Maker (...,Home&Kitchen|Kitchen&HomeAppliances|SmallKitch...,"₹2,863","₹3,690",22%,4.3,"6,987","Brand-Borosil, Specification â€“ 23V ~ 5Hz;1 W...","AFGW5PT3R6ZAVQR4Y5MWVAKBZAYA,AG7QNJ2SCS5VS5VYY...","Rajib,Ajay B,Vikas Kahol,PARDEEP,Anindya Prama...","R20RBRZ0WEUJT9,ROKIFK9R2ISSE,R30EEG2FNJSN5I,R2...","Works perfect,Ok good product,Nice Product. Re...",It does it job perfectly..only issue is temp c...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Borosil-Jumbo-1000-Watt-...

In [8]:
df.shape
df.describe
df.info

<bound method DataFrame.info of       product_id                                       product_name  \
0     B07JW9H4J1  Wayona Nylon Braided USB to Lightning Fast Cha...
1     B098NS6PVG  Ambrane Unbreakable 60W / 3A Fast Charging 1.5...
2     B096MSW6CT  Sounce Fast Phone Charging Cable & Data Sync U...
3     B08HDJ86NZ  boAt Deuce USB 300 2 in 1 Type-C & Micro USB S...
4     B08CF3B7N1  Portronics Konnect L 1.2M Fast Charging 3A 8 P...
...          ...                                                ...
1460  B08L7J3T31  Noir Aqua - 5pcs PP Spun Filter + 1 Spanner | ...
1461  B01M6453MB  Prestige Delight PRWO Electric Rice Cooker (1 ...
1462  B009P2LIL4  Bajaj Majesty RX10 2000 Watts Heat Convector R...
1463  B00J5DYCCA  Havells Ventil Air DSP 230mm Exhaust Fan (Pist...
1464  B01486F4G6  Borosil Jumbo 1000-Watt Grill Sandwich Maker (...

                                               category discounted_price  \
0     Computers&Accessories|Accessories&Peripherals|...             ₹399
1     Computers&Accessories|Accessories&Peripherals|...             ₹199
2     Computers&Accessories|Accessories&Peripherals|...             ₹199
3     Computers&Accessories|Accessories&Peripherals|...             ₹329
4     Computers&Accessories|Accessories&Peripherals|...             ₹154
...                                                 ...              ...
1460  Home&Kitchen|Kitchen&HomeAppliances|WaterPurif...             ₹379
1461  Home&Kitchen|Kitchen&HomeAppliances|SmallKitch...           ₹2,280
1462  Home&Kitchen|Heating,Cooling&AirQuality|RoomHe...           ₹2,219
1463  Home&Kitchen|Heating,Cooling&AirQuality|Fans|E...           ₹1,399
1464  Home&Kitchen|Kitchen&HomeAppliances|SmallKitch...           ₹2,863

     actual_price discount_percentage rating rating_count  \
0          ₹1,099                 64%    4.2       24,269
1            ₹349                 43%      4       43,994
2          ₹1,899                 90%    3.9        7,928
3            ₹699                 53%    4.2       94,363
4            ₹399                 61%    4.2       16,905
...           ...                 ...    ...          ...
1460         ₹919                 59%      4        1,090
1461       ₹3,045                 25%    4.1        4,118
1462       ₹3,080                 28%    3.6          468
1463       ₹1,890                 26%      4        8,031
1464       ₹3,690                 22%    4.3        6,987

                                          about_product  \
0     High Compatibility : Compatible With iPhone 12...
1     Compatible with all Type C enabled devices, be...
2     【 Fast Charger& Data Sync】-With built-in safet...
3     The boAt Deuce USB 300 2 in 1 cable is compati...
4     [CHARGE & SYNC FUNCTION]- This cable comes wit...
...                                                 ...
1460  SUPREME QUALITY 90 GRAM 3 LAYER THIK PP SPUN F...
1461                       230 Volts, 400 watts, 1 Year
1462  International design and styling|Two heat sett...
1463  Fan sweep area: 230 MM ; Noise level: (40 - 45...
1464  Brand-Borosil, Specification â€“ 23V ~ 5Hz;1 W...

                                                user_id  \
0     AG3D6O4STAQKAY2UVGEUV46KN35Q,AHMY5CWJMMK5BJRBB...
1     AECPFYFQVRUWC3KGNLJIOREFP5LQ,AGYYVPDD7YG7FYNBX...
2     AGU3BBQ2V2DDAMOAKGFAWDDQ6QHA,AESFLDV2PT363T2AQ...
3     AEWAZDZZJLQUYVOVGBEUKSLXHQ5A,AG5HTSFRRE6NL3M5S...
4     AE3Q6KSUK5P75D5HFYHCRAOLODSA,AFUGIFH5ZAFXRDSZH...
...                                                 ...
1460  AHITFY6AHALOFOHOZEOC6XBP4FEA,AFRABBODZJZQB6Z4U...
1461  AFG5FM3NEMOL6BNFRV2NK5FNJCHQ,AGEINTRN6Z563RMLH...
1462  AGVPWCMAHYQWJOQKMUJN4DW3KM5Q,AF4Q3E66MY4SR7YQZ...
1463  AF2JQCLSCY3QJATWUNNHUSVUPNQQ,AFDMLUXC5LS5RXDJS...
1464  AFGW5PT3R6ZAVQR4Y5MWVAKBZAYA,AG7QNJ2SCS5VS5VYY...

                                              user_name  \
0     Manav,Adarsh gupta,Sundeep,S.Sayeed Ahmed,jasp...
1     ArdKn,Nirbhay kumar,Sagar Viswanathan,Asp,Plac...
2     Kunal,Himanshu,viswanath,sai niharka,saqib mal...
3     Omkar dhale,JD,HEMALATHA,Ajwadh a.,amar singh ...
4     rahuls6099,Swasat Borah,Ajay Wadke,Pranali,RVK...
...                                                 ...
1460  Prabha ds,Raghuram bk,Real Deal,Amazon Custome...
1461  Manu Bhai,Naveenpittu,Evatira Sangma,JAGANNADH...
1462  Nehal Desai,Danish Parwez,Amazon Customer,Amaz...
1463  Shubham Dubey,E.GURUBARAN,Mayank S.,eusuf khan...
1464  Rajib,Ajay B,Vikas Kahol,PARDEEP,Anindya Prama...

                                              review_id  \
0     R3HXWT0LRP0NMF,R2AJM3LFTLZHFO,R6AQJGUP6P86,R1K...
1     RGIQEG07R9HS2,R1SMWZQ86XIN8U,R2J3Y1WL29GWDE,RY...
2     R3J3EQQ9TZI5ZJ,R3E7WBGK7ID0KV,RWU79XKQ6I1QF,R2...
3     R3EEUZKKK9J36I,R3HJVYCLYOY554,REDECAZ7AMPQC,R1...
4     R1BP4L2HH9TFUP,R16PVJEXKV6QZS,R2UPDB81N66T4P,R...
...                                                 ...
1460  R3G3XFHPBFF0E8,R3C0BZCD32EIGW,R2EBVBCN9QPD9R,R...
1461  R3DDL2UPKQ2CK9,R2SYYU1OATVIU5,R1VM993161IYRW,R...
1462  R1TLRJVW4STY5I,R2O455KRN493R1,R3Q5MVGBRIAS2G,R...
1463  R39Q2Y79MM9SWK,R3079BG1NIH6MB,R29A31ZELTZNJM,R...
1464  R20RBRZ0WEUJT9,ROKIFK9R2ISSE,R30EEG2FNJSN5I,R2...

                                           review_title  \
0     Satisfied,Charging is really fast,Value for mo...
1     A Good Braided Cable for Your Type C Device,Go...
2     Good speed for earlier versions,Good Product,W...
3     Good product,Good one,Nice,Really nice product...
4     As good as original,Decent,Good one for second...
...                                                 ...
1460  Received the product without spanner,Excellent...
1461  ok,everything was good couldn't return bcoz I ...
1462  very good,Work but front melt after 2 month,Go...
1463  Fan Speed is slow,Good quality,Good product,go...
1464  Works perfect,Ok good product,Nice Product. Re...

                                         review_content  \
0     Looks durable Charging is fine tooNo complains...
1     I ordered this cable to connect my phone to An...
2     Not quite durable and sturdy,https://m.media-a...
3     Good product,long wire,Charges good,Nice,I bou...
4     Bought this instead of original apple, does th...
...                                                 ...
1460  I received product without spanner,Excellent p...
1461  ok,got everything as mentioned but the measuri...
1462  plastic but cool body ,u have to find sturdy s...
1463  I have installed this in my kitchen working fi...
1464  It does it job perfectly..only issue is temp c...

                                               img_link  \
0     https://m.media-amazon.com/images/W/WEBP_40237...
1     https://m.media-amazon.com/images/W/WEBP_40237...
2     https://m.media-amazon.com/images/W/WEBP_40237...
3     https://m.media-amazon.com/images/I/41V5FtEWPk...
4     https://m.media-amazon.com/images/W/WEBP_40237...
...                                                 ...
1460  https://m.media-amazon.com/images/I/41fDdRtjfx...
1461  https://m.media-amazon.com/images/I/41gzDxk4+k...
1462  https://m.media-amazon.com/images/W/WEBP_40237...
1463  https://m.media-amazon.com/images/W/WEBP_40237...
1464  https://m.media-amazon.com/images/W/WEBP_40237...

                                           product_link
0     https://www.amazon.in/Wayona-Braided-WN3LG1-Sy...
1     https://www.amazon.in/Ambrane-Unbreakable-Char...
2     https://www.amazon.in/Sounce-iPhone-Charging-C...
3     https://www.amazon.in/Deuce-300-Resistant-Tang...
4     https://www.amazon.in/Portronics-Konnect-POR-1...
...                                                 ...
1460  https://www.amazon.in/Noir-Aqua-Spanner-Purifi...
1461  https://www.amazon.in/Prestige-Delight-PRWO-1-...
1462  https://www.amazon.in/Bajaj-RX-10-2000-Watt-Co...
1463  https://www.amazon.in/Havells-Ventilair-230mm-...
1464  https://www.amazon.in/Borosil-Jumbo-1000-Watt-...

[1465 rows x 16 columns]>

In [9]:
df.isnull().sum()

product_id             0
product_name           0
category               0
discounted_price       0
actual_price           0
discount_percentage    0
rating                 0
rating_count           2
about_product          0
user_id                0
user_name              0
review_id              0
review_title           0
review_content         0
img_link               0
product_link           0
dtype: int64

In [10]:
df['discounted_price'] = df['discounted_price'].str.replace('₹', '', regex=False).str.replace(',', '', regex=False).astype(float)
df['actual_price'] = df['actual_price'].str.replace('₹', '', regex=False).str.replace(',', '', regex=False).astype(float)

df['discount_percentage'] = df['discount_percentage'].str.replace('%', '', regex=False).astype(float)

df[['discounted_price', 'actual_price', 'discount_percentage']].head()
print(df.dtypes)

product_id              object
product_name            object
category                object
discounted_price       float64
actual_price           float64
discount_percentage    float64
rating                  object
rating_count            object
about_product           object
user_id                 object
user_name               object
review_id               object
review_title            object
review_content          object
img_link                object
product_link            object
dtype: object

In [11]:
le = LabelEncoder()

df['product_id'] = le.fit_transform(df['product_id'])
df['category'] = le.fit_transform(df['category'])

df.head()

,product_id,product_name,category,discounted_price,actual_price,discount_percentage,rating,rating_count,about_product,user_id,user_name,review_id,review_title,review_content,img_link,product_link
0,346,Wayona Nylon Braided USB to Lightning Fast Cha...,10,399.0,1099.0,64.0,4.2,"24,269",High Compatibility : Compatible With iPhone 12...,"AG3D6O4STAQKAY2UVGEUV46KN35Q,AHMY5CWJMMK5BJRBB...","Manav,Adarsh gupta,Sundeep,S.Sayeed Ahmed,jasp...","R3HXWT0LRP0NMF,R2AJM3LFTLZHFO,R6AQJGUP6P86,R1K...","Satisfied,Charging is really fast,Value for mo...",Looks durable Charging is fine tooNo complains...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Wayona-Braided-WN3LG1-Sy...
1,848,Ambrane Unbreakable 60W / 3A Fast Charging 1.5...,10,199.0,349.0,43.0,4,"43,994","Compatible with all Type C enabled devices, be...","AECPFYFQVRUWC3KGNLJIOREFP5LQ,AGYYVPDD7YG7FYNBX...","ArdKn,Nirbhay kumar,Sagar Viswanathan,Asp,Plac...","RGIQEG07R9HS2,R1SMWZQ86XIN8U,R2J3Y1WL29GWDE,RY...","A Good Braided Cable for Your Type C Device,Go...",I ordered this cable to connect my phone to An...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Ambrane-Unbreakable-Char...
2,819,Sounce Fast Phone Charging Cable & Data Sync U...,10,199.0,1899.0,90.0,3.9,"7,928",【 Fast Charger& Data Sync】-With built-in safet...,"AGU3BBQ2V2DDAMOAKGFAWDDQ6QHA,AESFLDV2PT363T2AQ...","Kunal,Himanshu,viswanath,sai niharka,saqib mal...","R3J3EQQ9TZI5ZJ,R3E7WBGK7ID0KV,RWU79XKQ6I1QF,R2...","Good speed for earlier versions,Good Product,W...","Not quite durable and sturdy,https://m.media-a...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Sounce-iPhone-Charging-C...
3,643,boAt Deuce USB 300 2 in 1 Type-C & Micro USB S...,10,329.0,699.0,53.0,4.2,"94,363",The boAt Deuce USB 300 2 in 1 cable is compati...,"AEWAZDZZJLQUYVOVGBEUKSLXHQ5A,AG5HTSFRRE6NL3M5S...","Omkar dhale,JD,HEMALATHA,Ajwadh a.,amar singh ...","R3EEUZKKK9J36I,R3HJVYCLYOY554,REDECAZ7AMPQC,R1...","Good product,Good one,Nice,Really nice product...","Good product,long wire,Charges good,Nice,I bou...",https://m.media-amazon.com/images/I/41V5FtEWPk...,https://www.amazon.in/Deuce-300-Resistant-Tang...
4,588,Portronics Konnect L 1.2M Fast Charging 3A 8 P...,10,154.0,399.0,61.0,4.2,"16,905",[CHARGE & SYNC FUNCTION]- This cable comes wit...,"AE3Q6KSUK5P75D5HFYHCRAOLODSA,AFUGIFH5ZAFXRDSZH...","rahuls6099,Swasat Borah,Ajay Wadke,Pranali,RVK...","R1BP4L2HH9TFUP,R16PVJEXKV6QZS,R2UPDB81N66T4P,R...","As good as original,Decent,Good one for second...","Bought this instead of original apple, does th...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Portronics-Konnect-POR-1...

In [12]:
columns_to_drop = [
    'product_name', 'rating', 'rating_count', 'about_product', 
    'user_id', 'user_name', 'review_id', 'review_title', 
    'img_link', 'product_link'
]

df_cleaned = df.drop(columns=columns_to_drop)

df_cleaned.head()

,product_id,category,discounted_price,actual_price,discount_percentage,review_content
0,346,10,399.0,1099.0,64.0,Looks durable Charging is fine tooNo complains...
1,848,10,199.0,349.0,43.0,I ordered this cable to connect my phone to An...
2,819,10,199.0,1899.0,90.0,"Not quite durable and sturdy,https://m.media-a..."
3,643,10,329.0,699.0,53.0,"Good product,long wire,Charges good,Nice,I bou..."
4,588,10,154.0,399.0,61.0,"Bought this instead of original apple, does th..."

In [13]:
df_cleaned = df_cleaned.drop(columns=['review_content'])
df_cleaned

,product_id,category,discounted_price,actual_price,discount_percentage
0,346,10,399.0,1099.0,64.0
1,848,10,199.0,349.0,43.0
2,819,10,199.0,1899.0,90.0
3,643,10,329.0,699.0,53.0
4,588,10,154.0,399.0,61.0
...,...,...,...,...,...
1460,673,192,379.0,919.0,59.0
1461,201,172,2280.0,3045.0,25.0
1462,27,138,2219.0,3080.0,28.0
1463,61,129,1399.0,1890.0,26.0
1464,134,174,2863.0,3690.0,22.0

In [14]:
df_cleaned['final_price'] = df_cleaned['actual_price'] - df_cleaned['discounted_price']
df_cleaned

,product_id,category,discounted_price,actual_price,discount_percentage,final_price
0,346,10,399.0,1099.0,64.0,700.0
1,848,10,199.0,349.0,43.0,150.0
2,819,10,199.0,1899.0,90.0,1700.0
3,643,10,329.0,699.0,53.0,370.0
4,588,10,154.0,399.0,61.0,245.0
...,...,...,...,...,...,...
1460,673,192,379.0,919.0,59.0,540.0
1461,201,172,2280.0,3045.0,25.0,765.0
1462,27,138,2219.0,3080.0,28.0,861.0
1463,61,129,1399.0,1890.0,26.0,491.0
1464,134,174,2863.0,3690.0,22.0,827.0

In [27]:
x = df_cleaned[["product_id", "category",	"discounted_price", "actual_price", "discount_percentage"]]
y = df_cleaned[["final_price"]]
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 42)

In [16]:
model = LinearRegression()
model.fit(x_train, y_train)

LinearRegression()

In [17]:
y_predict = model.predict(x_test)
model.predict([[201,172,2280.0,3045.0,25.0]])

C:\Users\Dell\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([[765.]])

In [18]:
mse = mean_squared_error(y_test, y_predict)
score = r2_score(y_test, y_predict)

In [19]:
print(f"Mean Squared Value: {mse:.2f}")
print(f"R2 Score is: {score:.2f}")

Mean Squared Value: 0.00
R2 Score is: 1.00

In [28]:
y_test_flat = y_test.values.flatten()
y_predict_flat = y_predict.flatten()

mean_absolute_err = np.mean(np.abs(y_predict_flat - y_test_flat))

mean_actual_val = np.mean(y_test_flat)

error_percentage = (mean_absolute_err / mean_actual_val) * 100

accuracy = 100 - error_percentage

print(f"Mean Absolute Error: {mean_absolute_err:.2f}")
print(f"Mean Actual Value: {mean_actual_val:.2f}")
print(f"Approximate Accuracy: {accuracy:.2f}%")

Mean Absolute Error: 0.00
Mean Actual Value: 2205.58
Approximate Accuracy: 100.00%